/* Content source notes: canonical verse order and orthography cross-checked against Vaidika Vignanam (https://vignanam.org/english/hanuman-chalisa.html) and the Art of Living English meaning page (https://www.artofliving.org/in-en/culture/reads/hanuman-chalisa-lyrics-meaning). */
export type ChalisaVerse = { n: string; hi: string; en: string; roman: string };

export const chalisaSources = [
  "https://vignanam.org/english/hanuman-chalisa.html",
  "https://www.artofliving.org/in-en/culture/reads/hanuman-chalisa-lyrics-meaning",
  "https://vignanam.org/marathi/hanuman-chalisa.html",
  "https://vignanam.org/bengali/hanuman-chalisa.html",
  "https://vignanam.org/tamil/hanuman-chalisa.html",
  "https://vignanam.org/telugu/hanuman-chalisa.html",
  "https://vignanam.org/gujarati/hanuman-chalisa.html",
  "https://vignanam.org/kannada/hanuman-chalisa.html",
  "https://vignanam.org/malayalam/hanuman-chalisa.html",
  "https://vignanam.org/punjabi/hanuman-chalisa.html",
];

export const verses: ChalisaVerse[] = [
  { n: "॥ दोहा ॥", hi: "श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि।\nबरनऊँ रघुबर बिमल जसु, जो दायकु फल चारि॥", en: "Having cleansed the mirror of my mind with the dust of my Guru's lotus feet, I sing the pure glory of Lord Rama, who grants the four fruits of life.", roman: "Shri guru charan saroja raja, nija manu mukuru sudhari.\nBaranau Raghubar bimala jasu, jo dayaku phala chari." },
  { n: "॥ दोहा ॥", hi: "बुद्धिहीन तनु जानिके, सुमिरौं पवन-कुमार।\nबल बुधि विद्या देहु मोहिं, हरहु कलेस बिकार॥", en: "Knowing my mind to be lacking in wisdom, I remember you, Son of the Wind. Grant me strength, understanding, and knowledge, and remove my afflictions and faults.", roman: "Buddhihin tanu janike, sumirau Pavan-kumar.\nBal buddhi vidya dehu mohi, harahu kalesh vikar." },
  { n: "१", hi: "जय हनुमान ज्ञान गुन सागर।\nजय कपीस तिहुँ लोक उजागर॥", en: "Victory to Hanuman, ocean of wisdom and virtue. Victory to the lord of monkeys, who illumines the three worlds.", roman: "Jai Hanuman gyan gun sagar.\nJai Kapis tihun lok ujagar." },
  { n: "२", hi: "राम दूत अतुलित बल धामा।\nअंजनि-पुत्र पवनसुत नामा॥", en: "You are Rama's messenger, the abode of incomparable strength, known as Anjani's son and the son of the Wind.", roman: "Ram doot atulit bal dhama.\nAnjani-putra Pavan-sut nama." },
  { n: "३", hi: "महाबीर बिक्रम बजरंगी।\nकुमति निवार सुमति के संगी॥", en: "Great hero, mighty as a thunderbolt, you remove harmful thoughts and keep company with wisdom.", roman: "Mahabir bikram Bajrangi.\nKumati nivar sumati ke sangi." },
  { n: "४", hi: "कंचन बरन बिराज सुबेसा।\nकानन कुण्डल कुंचित केसा॥", en: "Your golden form shines in beautiful attire, with earrings and curly hair.", roman: "Kanchan baran biraj subesa.\nKanan kundal kunchit kesa." },
  { n: "५", hi: "हाथ बज्र औ ध्वजा बिराजै।\nकाँधे मूँज जनेऊ साजै॥", en: "The thunderbolt and flag adorn your hands; the sacred thread rests upon your shoulder.", roman: "Hath bajra au dhvaja birajai.\nKandhe moonj janeu sajai." },
  { n: "६", hi: "शंकर सुवन केसरी नंदन।\nतेज प्रताप महा जग वंदन॥", en: "You are Shiva's embodiment and Kesari's son; your radiance and glory are revered throughout the world.", roman: "Shankar suvan Kesari nandan.\nTej pratap maha jag vandan." },
  { n: "७", hi: "विद्यावान गुनी अति चातुर।\nराम काज करिबे को आतुर॥", en: "Full of learning, virtue, and wisdom, you are always eager to perform Rama's work.", roman: "Vidyavan guni ati chatur.\nRam kaj karibe ko atur." },
  { n: "८", hi: "प्रभु चरित्र सुनिबे को रसिया।\nराम लखन सीता मन बसिया॥", en: "You delight in hearing the Lord's story; Rama, Lakshmana, and Sita dwell within your heart.", roman: "Prabhu charitra sunibe ko rasiya.\nRam Lakhan Sita man basiya." },
  { n: "९", hi: "सूक्ष्म रूप धरि सियहिं दिखावा।\nबिकट रूप धरि लंक जरावा॥", en: "You took a subtle form to reveal yourself to Sita, and a fearsome form to burn Lanka.", roman: "Sukshma roop dhari Siyahin dikhava.\nBikat roop dhari Lank jarava." },
  { n: "१०", hi: "भीम रूप धरि असुर संहारे।\nरामचंद्र के काज सँवारे॥", en: "Taking a mighty form, you destroyed the demons and fulfilled Lord Ramachandra's work.", roman: "Bhim roop dhari asur sanhare.\nRamchandra ke kaj sanvare." },
  { n: "११", hi: "लाय सजीवन लखन जियाए।\nश्रीरघुबीर हरषि उर लाए॥", en: "You brought the life-restoring herb and revived Lakshmana; joyful Rama embraced you.", roman: "Laye Sanjivan Lakhan jiyaye.\nShri Raghubir harashi ur laye." },
  { n: "१२", hi: "रघुपति कीन्ही बहुत बड़ाई।\nतुम मम प्रिय भरतहि सम भाई॥", en: "Rama praised you greatly and said, 'You are as dear to me as my brother Bharata.'", roman: "Raghupati keenhi bahut badai.\nTum mam priya Bharatahi sam bhai." },
  { n: "१३", hi: "सहस बदन तुम्हरो जस गावैं।\nअस कहि श्रीपति कंठ लगावैं॥", en: "The thousand-mouthed serpent sings your glory; saying this, Lord Rama drew you into an embrace.", roman: "Sahas badan tumharo jas gaven.\nAs kahi Shripati kanth lagaven." },
  { n: "१४", hi: "सनकादिक ब्रह्मादि मुनीसा।\nनारद सारद सहित अहीसा॥", en: "Sanaka and the sages, Brahma, Narada, Saraswati, and Shesha all sing your praise.", roman: "Sanakadik Brahmadi Munisa.\nNarad Sarad sahit Ahisa." },
  { n: "१५", hi: "जम कुबेर दिगपाल जहाँ ते।\nकबि कोबिद कहि सके कहाँ ते॥", en: "Yama, Kubera, the guardians of the directions, poets, and scholars cannot fully describe your glory.", roman: "Jam Kuber digpal jahan te.\nKabi kobid kahi sake kahan te." },
  { n: "१६", hi: "तुम उपकार सुग्रीवहिं कीन्हा।\nराम मिलाय राज पद दीन्हा॥", en: "You helped Sugriva meet Rama and restored him to his royal throne.", roman: "Tum upkar Sugrivahin keenha.\nRam milaye raj pad deenha." },
  { n: "१७", hi: "तुम्हरो मंत्र बिभीषण माना।\nलंकेश्वर भए सब जग जाना॥", en: "Vibhishana followed your counsel and became king of Lanka, as the whole world knows.", roman: "Tumharo mantra Vibhishan mana.\nLankeshwar bhaye sab jag jana." },
  { n: "१८", hi: "जुग सहस्र योजन पर भानू।\nलील्यो ताहि मधुर फल जानू॥", en: "You leapt toward the sun, thousands of leagues away, taking it to be a sweet fruit.", roman: "Yug sahasra yojan par Bhanu.\nLilyo tahi madhur phal janu." },
  { n: "१९", hi: "प्रभु मुद्रिका मेलि मुख माहीं।\nजलधि लाँघि गए अचरज नाहीं॥", en: "With Rama's ring in your mouth, you crossed the ocean; for you, this was no wonder.", roman: "Prabhu mudrika meli mukh mahi.\nJaladhi langhi gaye acharaj nahi." },
  { n: "२०", hi: "दुर्गम काज जगत के जेते।\nसुगम अनुग्रह तुम्हरे तेते॥", en: "All difficult tasks in the world become easy through your grace.", roman: "Durgam kaj jagat ke jete.\nSugam anugrah tumhare tete." },
  { n: "२१", hi: "राम दुआरे तुम रखवारे।\nहोत न आज्ञा बिनु पैसारे॥", en: "You guard the doorway of Rama; no one may enter without your permission.", roman: "Ram duare tum rakhvare.\nHot na agya binu paisare." },
  { n: "२२", hi: "सब सुख लहै तुम्हारी सरना।\nतुम रक्षक काहू को डरना॥", en: "Those who take refuge in you find every comfort; with you as protector, there is nothing to fear.", roman: "Sab sukh lahai tumhari sarna.\nTum rakshak kahu ko darna." },
  { n: "२३", hi: "आपन तेज सम्हारो आपै।\nतीनों लोक हाँक तें काँपै॥", en: "You alone can contain your own splendor; all three worlds tremble at your roar.", roman: "Aapan tej samharo aapai.\nTeenon lok hank te kanpai." },
  { n: "२४", hi: "भूत पिशाच निकट नहिं आवै।\nमहाबीर जब नाम सुनावै॥", en: "Ghosts and harmful forces do not come near when the name of the great hero is heard.", roman: "Bhoot pishach nikat nahi aavai.\nMahabir jab naam sunavai." },
  { n: "२५", hi: "नासै रोग हरै सब पीरा।\nजपत निरंतर हनुमत बीरा॥", en: "Illness and pain are dispelled for those who continually repeat the name of brave Hanuman.", roman: "Nasai rog harai sab peera.\nJapat nirantar Hanumat beera." },
  { n: "२६", hi: "संकट तें हनुमान छुड़ावै।\nमन क्रम बचन ध्यान जो लावै॥", en: "Hanuman frees from crisis those who remember him in thought, action, and word.", roman: "Sankat te Hanuman chudavai.\nMan kram vachan dhyan jo lavai." },
  { n: "२७", hi: "सब पर राम तपस्वी राजा।\nतिन के काज सकल तुम साजा॥", en: "Rama is supreme among kings and ascetics; you accomplish all of his tasks.", roman: "Sab par Ram tapasvi raja.\nTin ke kaj sakal tum saja." },
  { n: "२८", hi: "और मनोरथ जो कोई लावै।\nसोइ अमित जीवन फल पावै॥", en: "Whoever brings a sincere wish to you receives the enduring fruit of life.", roman: "Aur manorath jo koi lavai.\nSoi amit jeevan phal pavai." },
  { n: "२९", hi: "चारों जुग परताप तुम्हारा।\nहै परसिद्ध जगत उजियारा॥", en: "Your glory shines through all four ages and is renowned throughout the world.", roman: "Charon yug partap tumhara.\nHai parasiddh jagat ujiyara." },
  { n: "३०", hi: "साधु संत के तुम रखवारे।\nअसुर निकंदन राम दुलारे॥", en: "You protect saints and sages, destroy demons, and are beloved of Rama.", roman: "Sadhu sant ke tum rakhvare.\nAsur nikandan Ram dulare." },
  { n: "३१", hi: "अष्ट सिद्धि नौ निधि के दाता।\nअस बर दीन जानकी माता॥", en: "Mother Janaki granted you the power to bestow the eight siddhis and nine treasures.", roman: "Asht siddhi nau nidhi ke data.\nAs var deen Janaki mata." },
  { n: "३२", hi: "राम रसायन तुम्हरे पासा।\nसदा रहो रघुपति के दासा॥", en: "You possess the elixir of devotion to Rama; may you always remain Raghupati's servant.", roman: "Ram rasayan tumhare pasa.\nSada raho Raghupati ke dasa." },
  { n: "३३", hi: "तुम्हरे भजन राम को पावै।\nजनम जनम के दुख बिसरावै॥", en: "Through devotion to you, one finds Rama and forgets the sorrows of many births.", roman: "Tumhare bhajan Ram ko pavai.\nJanam janam ke dukh bisaravai." },
  { n: "३४", hi: "अंतकाल रघुवर पुर जाई।\nजहाँ जन्म हरि-भक्त कहाई॥", en: "At life's end, one reaches Rama's abode and is reborn as a devotee of Hari.", roman: "Antkal Raghuvar pur jai.\nJahan janam Hari-bhakt kahai." },
  { n: "३५", hi: "और देवता चित्त न धरई।\nहनुमत सेइ सर्व सुख करई॥", en: "One need not hold any other deity in mind; service to Hanuman brings every joy.", roman: "Aur devta chitt na dharai.\nHanumat sei sarv sukh karai." },
  { n: "३६", hi: "संकट कटै मिटै सब पीरा।\nजो सुमिरै हनुमत बलबीरा॥", en: "Troubles end and pain is removed for whoever remembers the mighty and courageous Hanuman.", roman: "Sankat katai mitai sab peera.\nJo sumirai Hanumat balbeera." },
  { n: "३७", hi: "जय जय जय हनुमान गोसाईं।\nकृपा करहु गुरुदेव की नाईं॥", en: "Victory, victory, victory to Lord Hanuman. Be gracious to me as a revered teacher.", roman: "Jai jai jai Hanuman Gosain.\nKripa karahu Gurudev ki nai." },
  { n: "३८", hi: "जो सत बार पाठ कर कोई।\nछूटहि बंदि महा सुख होई॥", en: "Whoever recites this a hundred times is freed from bondage and attains great joy.", roman: "Jo sat bar path kar koi.\nChhutahi bandi maha sukh hoi." },
  { n: "३९", hi: "जो यह पढ़ै हनुमान चालीसा।\nहोय सिद्धि साखी गौरीसा॥", en: "Whoever reads this Hanuman Chalisa attains fulfillment; Lord Shiva himself is witness.", roman: "Jo yah padhai Hanuman Chalisa.\nHoy siddhi sakhi Gaurisa." },
  { n: "४०", hi: "तुलसीदास सदा हरि चेरा।\nकीजै नाथ हृदय महँ डेरा॥", en: "Tulsidas remains forever Rama's servant; O Lord, make your dwelling in my heart.", roman: "Tulsidas sada Hari chera.\nKijai Nath hriday mah dera." },
  { n: "॥ समापन दोहा ॥", hi: "पवनतनय संकट हरन, मंगल मूरति रूप।\nराम लखन सीता सहित, हृदय बसहु सुर भूप॥", en: "O Son of the Wind, remover of troubles and embodiment of auspiciousness, dwell in my heart together with Rama, Lakshmana, and Sita.", roman: "Pavan-tanay sankat haran, mangal murti roop.\nRam Lakhan Sita sahit, hriday basahu sur bhoop." },
];

export const verseCount = 40;
